### PR TITLE
New feature, replace space to undersocre

### PR DESCRIPTION
**Pull request by Peter-Liang**
Hi Vlad:
Because sometimes I need to copy some words as variable name, so I added a new option to replace space to underscore. For example, replace ''some variable" to "some_variable". I made the option as option 27. TextFlow is a great tool and thank you for you work. Hope this feature can make TextFlow better :).
image

### CODE REVIEW

**Comment by vmdanilov** [comment]
Thanks @Peter-Liang.

To be honest, I'd like to keep developer stuff to a minimum. There's just too much to add. It's also much more productive to move that functionality to a code editor. Which one do you use?

**Comment by Peter-Liang** [comment]
Hi Vlad:
Thanks for your reply. I know this feature may be not commonly needed, it's fine. I just use this for my PyCharm.

**Comment by vmdanilov** [comment]
Just tried PyCharm, Macro feature is a disappointment.

Merging with some changes. Cheers.

**Comment by Peter-Liang** [comment]
Awesome, my first pull request has been accepted! Cheers.

**Pull request merged**
